# Generated by Django 4.0.4 on 2022-04-13 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testuser', '0002_addres_user_addres'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addres',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='addres',
            new_name='address',
        ),
    ]
